### ISSUE TITLE
Any plans to update this library for Xcode 11?

### ISSUE THREAD

**Issue by gingermcninja** [Innovid/tvos-framework-docs#1]
This library is no longer compatible with the latest version of Xcode - are there any plans to bring it up to date?

**Comment by lavenj** [comment]
@gingermcninja We actually do have Xcode 11 builds available, we just need to update the docs to reflect this. For 11.3.x, use this in your podspec:
```
pod 'InnovidAdRenderer_xcode11.3.0', '~> 1.5.21'
```
In general the pod name format is `InnovidAdRenderer_xcode<version>`, where version names are:
 - 10.1.0
 - 10.2.0
 - 10.3.0
 - 11.0.0
 - 11.2.1
 - 11.3.0

Let me know if you run into any problems updating to 1.5.x. The interface should be somewhere between similar and identical.

**Comment by gingermcninja** [comment]
Excellent, that's a great help, thanks
