### ISSUE TITLE
Need XCode 12 build

### ISSUE THREAD

**Issue by pete-alphero** [Innovid/tvos-framework-docs#2]
Please provide build for XCode 12.  We have other dependencies to use XCode 12 and require a compatible library from Innovid.

Thank you.

**Comment by pete-alphero** [comment]
Closing. Found https://github.com/Innovid/tvos-xcframework

**Comment by 7thsky** [comment]
@pete-alphero In case you still want to use `cocoapods` with XCode 12 
```
pod 'InnovidAdRenderer_xcode12.0.0', '~> 1.5.34'
```

**Comment by lavenj** [comment]
And please let us know if you run into any issues with the XCode 12 build process -- we've had to make some changes to the binary to work with XCode 12.
